all:

compile:
	javac Distance_Vector_Routing.java
	
runA:
	java Distance_Vector_Routing A configA.txt 2000

runB:
	java Distance_Vector_Routing B configB.txt 2001

runC:
	java Distance_Vector_Routing C configC.txt 2002

runD:
	java Distance_Vector_Routing D configD.txt 2003

runE:
	java Distance_Vector_Routing E configE.txt 2004

runF:
	java Distance_Vector_Routing F configF.txt 2005
